AutomatedTellerMachine/Controllers/CheckingAccountController.cs
using AutomatedTellerMachine.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AutomatedTellerMachine.Controllers
{
    public class CheckingAccountController : Controller
    {
        // GET: CheckingAccount
        public ActionResult Index()
        {
            return View();
        }

        // GET: CheckingAccount/Details
        public ActionResult Details()
        {
            var checkingAccount = new CheckingAccount { AccountNumber = "0000123456", FirstName = "Hizqeel", LastName = "Raza", Balance = 500 };
            return View(checkingAccount);
        }

        // GET: CheckingAccount/Create /processing the form
        public ActionResult Create()
        {
            return View();
        }

        // POST: CheckingAccount/Create /displaying the form
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CheckingAccount/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: CheckingAccount/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CheckingAccount/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CheckingAccount/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

AutomatedTellerMachine/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AutomatedTellerMachine.Controllers
{
    public class HomeController : Controller
    {
        // Attribute is not specified afer MyLoggingFilter because LoggingFilter.cs file is executing that method
        [MyLoggingFilter]
        public ActionResult Index()
        {
            //throw new StackOverflowException();
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.TheMessage = "Having Trouble? Send us a message";

            return View();
        }

        [HttpPost]
        public ActionResult Contact(string message)
        {
            //TODO: Send message to HQ
            ViewBag.TheMessage = "Thanks we got your message";

            return View();
        }


        public ActionResult Serial(string letterCase)
        {
            var serial = "ASPNETMVCATM1";
            if (letterCase == "lower")
            {
                return Content(serial.ToLower());
            }

           // return Content(serial);

          // return Json(new { name = "Serial", value = serial }, JsonRequestBehavior.AllowGet);

            return RedirectToAction("Index");
        }
    }
}

AutomatedTellerMachine/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<br />
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AutomatedTellerMachine/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<br />
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.TheMessage</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

<form method="post">
    <textarea name="message"></textarea>
    <input type="submit" name="submit" value="Send"/>
</form>

AutomatedTellerMachine/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    //Layout = "MyLayout.cshtml";
}
<br />

<div class="row">
    <div class="col-md-6 margin-top-20">
        <a href="#" class="btn btn-outline-primary btn-lg btn-block"><span class="fa fa-arrow-down"></span> Withdrawal</a>
        <a href="#" class="btn btn-outline-primary btn-lg btn-block"><span class="fa fa-dollar"></span> Quick Cash $100</a>
        <a href="@Url.Action("Details", "CheckingAccount")" class="btn btn-outline-primary btn-lg btn-block"><span class="fa fa-question"></span> Balance Inquiry</a>
        <br />
    </div>
    <div class="col-md-6 margin-top-20" >
        <a href="#" class="btn btn-outline-primary btn-lg btn-block"><span class="fa fa-print"></span> Print Statement</a>
        <a href="#" class="btn btn-outline-primary btn-lg btn-block"><span class="fa fa-money"></span> Transfer Funds</a>
        <a href="#" class="btn btn-outline-primary btn-lg btn-block"><span class="fa fa-arrow-up"></span> Deposit</a>
    </div>
</div>

@*
You are using @Request.Browser.Browser, its seems OK..! Cheers... :) <br />
Email me at example@mvc.com if you have any problem. or send me a tweet @@hizqeelrz.
*@
@*m is used here as suffix so that the doubles in the decimal are not used or treated as doubles.*@

@*
@{var amounts = new List<Decimal>{100, 25.50m, -40, 278.65m};}
*@

@*

<ul>
    <br />
    @foreach (decimal amount in amounts)
    {
        <li>@formatAmount(amount)</li>
    }
</ul>
@helper formatAmount(decimal amount) { 
    var color = "green";

    if (amount < 0)
    {
        color = "red";
    }
    <span style="color: @color" >@String.Format("{0:c}", amount)</span>
    }
*@